### PR TITLE
fix: compatibility with latest fastapi

### LINKED ISSUE #12: New fast api and pydantic error
Hi,
I would ike to try this project for personal use, I used to use Tus-go with docker Image, the project works fine with the requirements.txt provided in the root folder of the repo.

But with the latest fast api version and pydantic v2 I think things have moved somewhere, 

I have This error

```json
{
    "detail": [
        {
            "type": "missing",
            "loc": [
                "query",
                "args"
            ],
            "msg": "Field required",
            "input": null,
            "url": "https://errors.pydantic.dev/2.5/v/missing"
        },
        {
            "type": "missing",
            "loc": [
                "query",
                "kwargs"
            ],
            "msg": "Field required",
            "input": null,
            "url": "https://errors.pydantic.dev/2.5/v/missing"
        }
    ]
}
```
and my requirements.txt is the following:

```
annotated-types==0.6.0
anyio==3.7.1
certifi==2023.11.17
click==8.1.7
dnspython==2.4.2
email-validator==2.1.0.post1
fastapi==0.104.1
h11==0.14.0
httpcore==1.0.2
httptools==0.6.1
httpx==0.25.1
idna==3.4
itsdangerous==2.1.2
Jinja2==3.1.2
MarkupSafe==2.1.3
orjson==3.9.10
pydantic==2.5.1
pydantic-extra-types==2.1.0
pydantic-settings==2.1.0
pydantic_core==2.14.3
python-dotenv==1.0.0
python-multipart==0.0.6
PyYAML==6.0.1
sniffio==1.3.0
starlette==0.27.0
tuspyserver==1.3.1
typing_extensions==4.8.0
ujson==5.8.0
uvicorn==0.24.0.post1
uvloop==0.19.0
watchfiles==0.21.0
websockets==12.0
```

PS: I would like to contribute to this project, but I dont know where the problem is in the code-source

Thank you very much

### PR DESCRIPTION
**Pull request by jarey**
compatibility with latest fastapi versions

fixes #12

### CODE REVIEW

**Review by edihasaj — APPROVED** [review]

**Comment by edihasaj** [comment]
thank you very much for your contribution @jarey

**Comment by jarey** [comment]
> thank you very much for your contribution @jarey

You're welcome! Thanks fyou @edihasaj for mantaining this open-source repo.

Just wanted to keep the discussion here in order to keep the context. I think latest 2.0.0 was not needed, as changes were compatible between the range of pydantic 1 and pydantic 2, also between the already supported versions of fastapi and latest available ones.

I would say the release could have been 1.3.2 or 1.4.0 as the interfaces are kept the same.

Jus wanted to place my 2 cents here and avoid forgetting.

Kind regards.

**Comment by edihasaj** [comment]
Yes, I will deploy then a 1.3.2 for the pydantic v1

**Comment by edihasaj** [comment]
@jarey I just uploaded the 1.3.2 that includes your fixes and pydantic v1 etc.

**Pull request merged**
